# Generated by Django 5.1.1 on 2024-09-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRestuarant',
            new_name='UserRestaurant',
        ),
        migrations.AlterUniqueTogether(
            name='userrestaurant',
            unique_together={('user', 'restaurant')},
        ),
    ]
