# Generated by Django 5.1.1 on 2024-09-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_rename_userrestuarant_userrestaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestaurant',
            name='restaurant',
            field=models.TextField(),
        ),
    ]
