# Generated by Django 5.1.1 on 2024-09-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_alter_userrestaurant_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrestaurant',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
        migrations.AlterUniqueTogether(
            name='userrestaurant',
            unique_together={('user', 'restaurant_id')},
        ),
    ]
